### ISSUE TITLE
Unable to import module error once deployed

### ISSUE THREAD

**Issue by araines** [alexcasalboni/serverless-starter-python#2]
Just tried to use this from scratch today, and the Continent endpoint does not work once deployed.

```
{"errorMessage": "Unable to import module 'continent/_serverless_handler'"}
```
### Steps to recreate

Clone the repository and initialise the project:

```
git clone git@github.com:alexcasalboni/serverless-starter-python.git
cd serverless-starter-python
serverless project init
```

Deploy (selecting the Continent function and endpoint to deploy).

```
serverless dash deploy
```

```
Serverless: Deploying the specified functions in "dev" to the following regions: eu-west-1
Serverless: ------------------------
Serverless: Successfully deployed the following functions in "dev" to the following regions:
Serverless: eu-west-1 ------------------------
Serverless:   continent (serverless-starter-python-continent): arn:aws:lambda:eu-west-1:263804027495:function:serverless-starter-python-continent:dev

Serverless: Deploying endpoints in "dev" to the following regions: eu-west-1
Serverless: Successfully deployed endpoints in "dev" to the following regions:
Serverless: eu-west-1 ------------------------
Serverless:   GET - continent - https://ad599t3opc.execute-api.eu-west-1.amazonaws.com/dev/continent
```

**Comment by alexcasalboni** [comment]
Hi @araines,

sorry for the late response.

I can confirm the bug, and it's pretty weird because of how the function is defined [here](https://github.com/alexcasalboni/serverless-starter-python/blob/master/restApi/continent/s-function.json#L7). The handler should be `continent/handler.handler`, although the handler I see on the AWS Console is `continent/_serverless_handler.handler`.

The same happens if you deploy the multi/create function (the deployed handler will be `multi/create/_serverless_handler`). I guess sls expects the configured handler to always be `handler.handler` and performs some kind of wrapping.

Indeed, the bug is related to the [main repository](https://github.com/serverless/serverless): the same issue was reported [here](https://github.com/serverless/serverless/issues/1209) a few weeks ago and the bug wasn't there yet when I published this repo.

**Comment by alexcasalboni** [comment]
Hey @araines,

quick update: it seems like there is no bug. I was inspecting the Lambda function's code (you can download it with "Actions > Download function code") and I noticed that all the requirements are missing (see the `vendored` folder).

My bad here, this step is not mentioned in the documentation at all. I'm going to add it right now.

Here is what you need to do in order to install your Python dependencies.

```
cd restApi
pip install -t vendored/ -r requirements.txt
```

Alternatively you can use a virtualenv (recommended, but be careful with the last step as you don't want to actually copy everything, including setuptools, pip, easy_install, etc.):

```
cd restApi
virtualenv myenv
source myenv/bin/activate
pip install -r requirements.txt
cp -R myenv/lib/python2.7/site-packages/* vendored/
```

Looking back at the error message, the interpreter couldn't import `continent/_serverless_handler` just because it imports `continent/handler.handler`, which imports `lib/continent`, which imports the `countrycode` dependency.

Indeed, when I downloaded the Lambda code and tried this:

```
cd continent
python
>>> from _serverless_handler import handler
```

I finally received the following error:

```
ImportError: No module named countrycode
```
